---
linters:
  PropertySortOrder:
    order: recess

  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false

  PlaceholderInExtend:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
